/**
 * SmarterMail adapter — the parts that fail quietly.
 *
 * Token caching is the reason this file exists: a cache that never expires
 * works perfectly for an hour and then fails on a task that has been running
 * all night, and a cache that never hits re-authenticates on every call and
 * writes a login record each time. Neither shows up in a manual test.
 */

import { afterEach, describe, expect, it, vi } from 'vitest';
import { __clearTokenCache, buildUrl, guardPath, parseCredential } from '@/libs/plugins/smartermail';

afterEach(() => {
  __clearTokenCache();
  vi.unstubAllGlobals();
  vi.useRealTimers();
});

describe('parseCredential', () => {
  it('splits username and password', () => {
    expect(parseCredential('artivio@example.com:hunter2')).toEqual({
      username: 'artivio@example.com',
      password: 'hunter2',
    });
  });

  /**
   * The password is everything after the FIRST colon. Mail-server passwords
   * are generated by password managers and routinely contain colons; splitting
   * on all of them would truncate silently and surface as "the username or
   * password was rejected", sending someone to re-check a correct password.
   */
  it('keeps a password that contains colons', () => {
    expect(parseCredential('user@x.com:a:b:c').password).toBe('a:b:c');
  });

  /**
   * Both halves of the same decision. A pasted credential carries a trailing
   * newline and that must go; a trailing SPACE is a legal password character
   * and must not, because trimming it fails authentication forever with an
   * error that blames the password.
   */
  it('keeps a trailing space in the password', () => {
    expect(parseCredential('user@x.com:secret ').password).toBe('secret ');
  });

  it('strips a pasted trailing newline', () => {
    expect(parseCredential('user@x.com:secret\n').password).toBe('secret');
    expect(parseCredential('\nuser@x.com:secret\r\n').username).toBe('user@x.com');
  });

  it.each(['', 'nocolon', ':password', 'user@x.com:'])('rejects %j', (input) => {
    expect(() => parseCredential(input)).toThrow(/SmarterMail/);
  });

  it('explains that SmarterMail has no API keys', () => {
    expect(() => parseCredential('nocolon')).toThrow(/does not issue API keys/);
  });
});

describe('buildUrl', () => {
  it.each([
    ['settings/domain/data'],
    ['/settings/domain/data'],
    ['/api/v1/settings/domain/data'],
    ['api/v1/settings/domain/data'],
  ])('normalises %s to one absolute URL', (path) => {
    expect(buildUrl('https://mail.example.com', path)).toBe(
      'https://mail.example.com/api/v1/settings/domain/data',
    );
  });

  it('tolerates a trailing slash on the server', () => {
    expect(buildUrl('https://mail.example.com/', 'auth/authenticate-user')).toBe(
      'https://mail.example.com/api/v1/auth/authenticate-user',
    );
  });

  // A future build could expose /api/v2. Prefixing it with /api/v1 would turn
  // a valid path into a 404 that reads like a missing feature.
  it('leaves an explicit api version alone', () => {
    expect(buildUrl('https://mail.example.com', '/api/v2/thing')).toBe(
      'https://mail.example.com/api/v2/thing',
    );
  });

  it('refuses when the connection has no server URL', () => {
    expect(() => buildUrl(undefined, 'settings/domain/data')).toThrow(/no server URL/);
  });

  it('refuses an empty path', () => {
    expect(() => buildUrl('https://mail.example.com', '   ')).toThrow(/no API path/);
  });
});

describe('guardPath', () => {
  it('allows ordinary reads and writes', () => {
    expect(() => guardPath('GET', 'settings/sysadmin/domains', false)).not.toThrow();
    expect(() => guardPath('POST', 'settings/sysadmin/user-put', false)).not.toThrow();
  });

  it.each([
    'settings/sysadmin/user-delete',
    'settings/domain/alias-remove',
    'settings/sysadmin/domain-disable',
    'settings/sysadmin/clear-spool',
  ])('blocks %s by default', (path) => {
    expect(() => guardPath('POST', path, false)).toThrow(/blocked by default/);
  });

  it('lets a confirmed destructive call through', () => {
    expect(() => guardPath('POST', 'settings/sysadmin/user-delete', true)).not.toThrow();
  });

  /**
   * A GET cannot destroy anything, and blocking one on the word "delete"
   * would refuse to LIST the deleted items — a guard that blocks the
   * diagnosis of the thing it is guarding against is worse than no guard.
   */
  it('does not block a GET whose path merely contains a destructive word', () => {
    expect(() => guardPath('GET', 'settings/sysadmin/deleted-users', false)).not.toThrow();
  });

  /**
   * Impersonation signs in AS a mailbox owner and can read their mail. No
   * troubleshooting task needs that, and the result would persist in a
   * transcript — so the confirmation flag must not open it.
   */
  it('blocks impersonation with and without confirmation', () => {
    expect(() => guardPath('POST', 'settings/domain/impersonate-user', false)).toThrow(/cannot be enabled/);
    expect(() => guardPath('POST', 'settings/domain/impersonate-user', true)).toThrow(/cannot be enabled/);
  });

  it('blocks impersonation even on a GET', () => {
    expect(() => guardPath('GET', 'settings/domain/impersonate-user', false)).toThrow(/cannot be enabled/);
  });

  it('phrases refusals so classifyToolError sees a client-fixable fault', () => {
    // "blocked by default" and "cannot be enabled" are ours to explain; the
    // path-missing case must not read as an Artivio bug.
    expect(() => buildUrl('https://mail.example.com', '')).toThrow(/rejected the request/);
  });
});

/**
 * Token lifecycle. These use a stubbed fetch rather than a real server —
 * the behaviour under test is ours, not SmarterMail's.
 */
describe('token caching', () => {
  const CRED = 'artivio@example.com:hunter2';
  const SERVER = 'https://mail.example.com';

  /** A fetch stub that records calls and replies per URL. */
  function stubFetch(options?: { expiresInMs?: number; apiStatus?: number[] }) {
    const calls: Array<{ url: string; method: string }> = [];
    const apiStatuses = [...(options?.apiStatus ?? [])];

    const fetchMock = vi.fn(async (url: string, init?: any) => {
      calls.push({ url: String(url), method: init?.method ?? 'GET' });

      if (String(url).includes('auth/authenticate-user')) {
        return new Response(JSON.stringify({
          accessToken: `tok-${calls.length}`,
          accessTokenExpiration: new Date(Date.now() + (options?.expiresInMs ?? 3600_000)).toISOString(),
        }), { status: 200 });
      }

      const status = apiStatuses.shift() ?? 200;
      return new Response(JSON.stringify({ success: true, ok: true }), { status });
    });

    vi.stubGlobal('fetch', fetchMock);
    return calls;
  }

  it('authenticates once, then reuses the token', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubFetch();

    await smartermailProvider.call('list_domains', {}, CRED, SERVER);
    await smartermailProvider.call('list_domains', {}, CRED, SERVER);
    await smartermailProvider.call('list_domains', {}, CRED, SERVER);

    const auths = calls.filter(c => c.url.includes('authenticate-user'));

    expect(auths).toHaveLength(1);
    expect(calls).toHaveLength(4); // 1 auth + 3 API calls
  });

  /**
   * A token about to lapse is worse than no token: it passes the check, then
   * the request fails mid-task. EXPIRY_MARGIN_MS exists to re-authenticate
   * early, and this is the test that it actually does.
   */
  it('re-authenticates a token that is within the expiry margin', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    // 30s of life left, margin is 60s — must not be reused.
    const calls = stubFetch({ expiresInMs: 30_000 });

    await smartermailProvider.call('list_domains', {}, CRED, SERVER);
    await smartermailProvider.call('list_domains', {}, CRED, SERVER);

    expect(calls.filter(c => c.url.includes('authenticate-user'))).toHaveLength(2);
  });

  it('caches per server and account, not globally', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubFetch();

    await smartermailProvider.call('list_domains', {}, CRED, SERVER);
    await smartermailProvider.call('list_domains', {}, CRED, 'https://mail2.example.com');
    await smartermailProvider.call('list_domains', {}, 'other@example.com:pw', SERVER);

    expect(calls.filter(c => c.url.includes('authenticate-user'))).toHaveLength(3);
  });

  /**
   * A cached token can be invalidated server-side by a restart or a password
   * change. One retry with a fresh token is right; retrying forever on a
   * permissions failure is how an account gets locked out.
   */
  it('retries once with a fresh token on a 401, and not more', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubFetch({ apiStatus: [401, 401] });

    await expect(smartermailProvider.call('list_domains', {}, CRED, SERVER)).rejects.toThrow(/HTTP 401/);

    // auth, api(401), auth, api(401) — and then it stops.
    expect(calls.filter(c => c.url.includes('authenticate-user'))).toHaveLength(2);
    expect(calls).toHaveLength(4);
  });

  it('recovers when the retry succeeds', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubFetch({ apiStatus: [401, 200] });

    await expect(smartermailProvider.call('list_domains', {}, CRED, SERVER)).resolves.toContain('ok');
    expect(calls).toHaveLength(4);
  });
});

describe('failures that arrive as HTTP 200', () => {
  const CRED = 'artivio@example.com:hunter2';
  const SERVER = 'https://mail.example.com';

  /**
   * 🔴 A wrong password comes back 200 OK with no accessToken. Left alone,
   * the next call fails on an undefined token and the error points at our
   * code rather than at the password.
   */
  it('names the sign-in failure instead of failing later on an undefined token', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    vi.stubGlobal('fetch', vi.fn(async () => new Response(
      JSON.stringify({ success: false, message: 'Authentication failed' }),
      { status: 200 },
    )));

    await expect(smartermailProvider.call('list_domains', {}, CRED, SERVER))
      .rejects
      .toThrow(/rejected the sign-in .* Authentication failed/);
  });

  it('treats success:false on an API call as a failure', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    vi.stubGlobal('fetch', vi.fn(async (url: string) => new Response(
      String(url).includes('authenticate-user')
        ? JSON.stringify({ accessToken: 'tok', accessTokenExpiration: new Date(Date.now() + 3600_000).toISOString() })
        : JSON.stringify({ success: false, message: 'Domain not found' }),
      { status: 200 },
    )));

    await expect(smartermailProvider.call('get_domain', { domain: 'nope.org' }, CRED, SERVER))
      .rejects
      .toThrow(/rejected the request .* Domain not found/);
  });

  it('points a 404 at this server\'s own API documentation', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    vi.stubGlobal('fetch', vi.fn(async (url: string) => (String(url).includes('authenticate-user')
      ? new Response(JSON.stringify({ accessToken: 'tok', accessTokenExpiration: new Date(Date.now() + 3600_000).toISOString() }), { status: 200 })
      : new Response('not found', { status: 404 }))));

    await expect(smartermailProvider.call('list_domains', {}, CRED, SERVER))
      .rejects
      .toThrow(/Documentation\/api/);
  });
});
