/**
 * SmarterMail adapter — the parts that fail quietly.
 *
 * Token caching is the reason this file exists: a cache that never expires
 * works perfectly for an hour and then fails on a task that has been running
 * all night, and a cache that never hits re-authenticates on every call and
 * writes a login record each time. Neither shows up in a manual test.
 */

import { afterEach, describe, expect, it, vi } from 'vitest';
import { __clearTokenCache, buildUrl, guardPath, parseCredential, parseTarget } from '@/libs/plugins/smartermail';

afterEach(() => {
  __clearTokenCache();
  vi.unstubAllGlobals();
  vi.useRealTimers();
});

describe('parseCredential', () => {
  it('splits username and password', () => {
    expect(parseCredential('artivio@example.com:hunter2')).toEqual({
      username: 'artivio@example.com',
      password: 'hunter2',
    });
  });

  /**
   * The password is everything after the FIRST colon. Mail-server passwords
   * are generated by password managers and routinely contain colons; splitting
   * on all of them would truncate silently and surface as "the username or
   * password was rejected", sending someone to re-check a correct password.
   */
  it('keeps a password that contains colons', () => {
    expect(parseCredential('user@x.com:a:b:c').password).toBe('a:b:c');
  });

  /**
   * Both halves of the same decision. A pasted credential carries a trailing
   * newline and that must go; a trailing SPACE is a legal password character
   * and must not, because trimming it fails authentication forever with an
   * error that blames the password.
   */
  it('keeps a trailing space in the password', () => {
    expect(parseCredential('user@x.com:secret ').password).toBe('secret ');
  });

  it('strips a pasted trailing newline', () => {
    expect(parseCredential('user@x.com:secret\n').password).toBe('secret');
    expect(parseCredential('\nuser@x.com:secret\r\n').username).toBe('user@x.com');
  });

  it.each(['', 'nocolon', ':password', 'user@x.com:'])('rejects %j', (input) => {
    expect(() => parseCredential(input)).toThrow(/SmarterMail/);
  });

  it('explains that SmarterMail has no API keys', () => {
    expect(() => parseCredential('nocolon')).toThrow(/does not issue API keys/);
  });
});

describe('buildUrl', () => {
  it.each([
    ['settings/domain/data'],
    ['/settings/domain/data'],
    ['/api/v1/settings/domain/data'],
    ['api/v1/settings/domain/data'],
  ])('normalises %s to one absolute URL', (path) => {
    expect(buildUrl('https://mail.example.com', path)).toBe(
      'https://mail.example.com/api/v1/settings/domain/data',
    );
  });

  it('tolerates a trailing slash on the server', () => {
    expect(buildUrl('https://mail.example.com/', 'auth/authenticate-user')).toBe(
      'https://mail.example.com/api/v1/auth/authenticate-user',
    );
  });

  // A future build could expose /api/v2. Prefixing it with /api/v1 would turn
  // a valid path into a 404 that reads like a missing feature.
  it('leaves an explicit api version alone', () => {
    expect(buildUrl('https://mail.example.com', '/api/v2/thing')).toBe(
      'https://mail.example.com/api/v2/thing',
    );
  });

  it('refuses when the connection has no server URL', () => {
    expect(() => buildUrl(undefined, 'settings/domain/data')).toThrow(/no server URL/);
  });

  it('refuses an empty path', () => {
    expect(() => buildUrl('https://mail.example.com', '   ')).toThrow(/no API path/);
  });
});

describe('guardPath', () => {
  it('allows ordinary reads and writes', () => {
    expect(() => guardPath('GET', 'settings/sysadmin/domains', false)).not.toThrow();
    expect(() => guardPath('POST', 'settings/sysadmin/user-put', false)).not.toThrow();
  });

  it.each([
    'settings/sysadmin/user-delete',
    'settings/domain/alias-remove',
    'settings/sysadmin/domain-disable',
    'settings/sysadmin/clear-spool',
  ])('blocks %s by default', (path) => {
    expect(() => guardPath('POST', path, false)).toThrow(/blocked by default/);
  });

  it('lets a confirmed destructive call through', () => {
    expect(() => guardPath('POST', 'settings/sysadmin/user-delete', true)).not.toThrow();
  });

  /**
   * A GET cannot destroy anything, and blocking one on the word "delete"
   * would refuse to LIST the deleted items — a guard that blocks the
   * diagnosis of the thing it is guarding against is worse than no guard.
   */
  it('does not block a GET whose path merely contains a destructive word', () => {
    expect(() => guardPath('GET', 'settings/sysadmin/deleted-users', false)).not.toThrow();
  });

  /**
   * Impersonation signs in AS a mailbox owner and can read their mail. No
   * troubleshooting task needs that, and the result would persist in a
   * transcript — so the confirmation flag must not open it.
   */
  it('blocks impersonation with and without confirmation', () => {
    expect(() => guardPath('POST', 'settings/domain/impersonate-user', false)).toThrow(/cannot be enabled/);
    expect(() => guardPath('POST', 'settings/domain/impersonate-user', true)).toThrow(/cannot be enabled/);
  });

  it('blocks impersonation even on a GET', () => {
    expect(() => guardPath('GET', 'settings/domain/impersonate-user', false)).toThrow(/cannot be enabled/);
  });

  it('phrases refusals so classifyToolError sees a client-fixable fault', () => {
    // "blocked by default" and "cannot be enabled" are ours to explain; the
    // path-missing case must not read as an Artivio bug.
    expect(() => buildUrl('https://mail.example.com', '')).toThrow(/rejected the request/);
  });
});

/**
 * Token lifecycle. These use a stubbed fetch rather than a real server —
 * the behaviour under test is ours, not SmarterMail's.
 */
describe('token caching', () => {
  const CRED = 'artivio@example.com:hunter2';
  const SERVER = 'https://mail.example.com';

  /** A fetch stub that records calls and replies per URL. */
  function stubFetch(options?: { expiresInMs?: number; apiStatus?: number[] }) {
    const calls: Array<{ url: string; method: string }> = [];
    const apiStatuses = [...(options?.apiStatus ?? [])];

    const fetchMock = vi.fn(async (url: string, init?: any) => {
      calls.push({ url: String(url), method: init?.method ?? 'GET' });

      if (String(url).includes('auth/authenticate-user')) {
        return new Response(JSON.stringify({
          accessToken: `tok-${calls.length}`,
          accessTokenExpiration: new Date(Date.now() + (options?.expiresInMs ?? 3600_000)).toISOString(),
        }), { status: 200 });
      }

      const status = apiStatuses.shift() ?? 200;
      return new Response(JSON.stringify({ success: true, ok: true }), { status });
    });

    vi.stubGlobal('fetch', fetchMock);
    return calls;
  }

  it('authenticates once, then reuses the token', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubFetch();

    await smartermailProvider.call('list_domains', {}, CRED, SERVER);
    await smartermailProvider.call('list_domains', {}, CRED, SERVER);
    await smartermailProvider.call('list_domains', {}, CRED, SERVER);

    const auths = calls.filter(c => c.url.includes('authenticate-user'));

    expect(auths).toHaveLength(1);
    expect(calls).toHaveLength(4); // 1 auth + 3 API calls
  });

  /**
   * A token about to lapse is worse than no token: it passes the check, then
   * the request fails mid-task. EXPIRY_MARGIN_MS exists to re-authenticate
   * early, and this is the test that it actually does.
   */
  it('re-authenticates a token that is within the expiry margin', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    // 30s of life left, margin is 60s — must not be reused.
    const calls = stubFetch({ expiresInMs: 30_000 });

    await smartermailProvider.call('list_domains', {}, CRED, SERVER);
    await smartermailProvider.call('list_domains', {}, CRED, SERVER);

    expect(calls.filter(c => c.url.includes('authenticate-user'))).toHaveLength(2);
  });

  it('caches per server and account, not globally', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubFetch();

    await smartermailProvider.call('list_domains', {}, CRED, SERVER);
    await smartermailProvider.call('list_domains', {}, CRED, 'https://mail2.example.com');
    await smartermailProvider.call('list_domains', {}, 'other@example.com:pw', SERVER);

    expect(calls.filter(c => c.url.includes('authenticate-user'))).toHaveLength(3);
  });

  /**
   * A cached token can be invalidated server-side by a restart or a password
   * change. One retry with a fresh token is right; retrying forever on a
   * permissions failure is how an account gets locked out.
   */
  it('retries once with a fresh token on a 401, and not more', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubFetch({ apiStatus: [401, 401] });

    await expect(smartermailProvider.call('list_domains', {}, CRED, SERVER)).rejects.toThrow(/HTTP 401/);

    // auth, api(401), auth, api(401) — and then it stops.
    expect(calls.filter(c => c.url.includes('authenticate-user'))).toHaveLength(2);
    expect(calls).toHaveLength(4);
  });

  it('recovers when the retry succeeds', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubFetch({ apiStatus: [401, 200] });

    await expect(smartermailProvider.call('list_domains', {}, CRED, SERVER)).resolves.toContain('ok');
    expect(calls).toHaveLength(4);
  });
});

describe('failures that arrive as HTTP 200', () => {
  const CRED = 'artivio@example.com:hunter2';
  const SERVER = 'https://mail.example.com';

  /**
   * 🔴 A wrong password comes back 200 OK with no accessToken. Left alone,
   * the next call fails on an undefined token and the error points at our
   * code rather than at the password.
   */
  it('names the sign-in failure instead of failing later on an undefined token', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    vi.stubGlobal('fetch', vi.fn(async () => new Response(
      JSON.stringify({ success: false, message: 'Authentication failed' }),
      { status: 200 },
    )));

    await expect(smartermailProvider.call('list_domains', {}, CRED, SERVER))
      .rejects
      .toThrow(/rejected the sign-in .* Authentication failed/);
  });

  it('treats success:false on an API call as a failure', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    vi.stubGlobal('fetch', vi.fn(async (url: string) => new Response(
      String(url).includes('authenticate-user')
        ? JSON.stringify({ accessToken: 'tok', accessTokenExpiration: new Date(Date.now() + 3600_000).toISOString() })
        : JSON.stringify({ success: false, message: 'Domain not found' }),
      { status: 200 },
    )));

    await expect(smartermailProvider.call('get_domain', { domain: 'nope.org' }, CRED, SERVER))
      .rejects
      .toThrow(/rejected the request .* Domain not found/);
  });

  it('points a 404 at this server\'s own API documentation', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    vi.stubGlobal('fetch', vi.fn(async (url: string) => (String(url).includes('authenticate-user')
      ? new Response(JSON.stringify({ accessToken: 'tok', accessTokenExpiration: new Date(Date.now() + 3600_000).toISOString() }), { status: 200 })
      : new Response('not found', { status: 404 }))));

    await expect(smartermailProvider.call('list_domains', {}, CRED, SERVER))
      .rejects
      .toThrow(/Documentation\/api/);
  });
});

/**
 * Domain-scoped tools.
 *
 * These are the regression tests for a bug that shipped and stayed invisible:
 * `domain_users` and `list_aliases` passed the domain in the PATH, but
 * SmarterMail scopes `settings/domain/*` to the token, and a system
 * administrator belongs to no domain. So both failed on every server, and the
 * failure ("The domain not found" / a 404) read as though the build simply did
 * not expose the endpoint. It was reported as a missing feature.
 *
 * What matters here is not the happy path but that we impersonate a domain
 * ADMIN and stop — never a mailbox owner, and never against a mail endpoint.
 */
describe('domain-scoped tools', () => {
  const CRED = 'artivio@example.com:hunter2';
  const SERVER = 'https://mail.example.com';

  /** Auth → domain-admins → impersonate → the domain-scoped call. */
  function stubDomainFlow(opts?: {
    admins?: unknown;
    onDomainCall?: (url: string, token: string) => Response;
  }) {
    const calls: Array<{ url: string; token: string; body?: any }> = [];
    const spy = vi.fn(async (url: string, init?: any) => {
      const u = String(url);
      const token = String(init?.headers?.Authorization ?? '').replace('Bearer ', '');
      calls.push({ url: u, token, body: init?.body ? JSON.parse(init.body) : undefined });

      if (u.includes('authenticate-user')) {
        return new Response(JSON.stringify({
          accessToken: 'sysadmin-token',
          accessTokenExpiration: new Date(Date.now() + 3600_000).toISOString(),
        }), { status: 200 });
      }
      if (u.includes('domain-admins')) {
        return new Response(JSON.stringify(
          opts?.admins ?? { domainAdmins: [{ userName: 'admin@budgetsmart.io' }] },
        ), { status: 200 });
      }
      if (u.includes('impersonate-user')) {
        return new Response(JSON.stringify({ impersonateAccessToken: 'domain-token' }), { status: 200 });
      }
      if (opts?.onDomainCall) {
        return opts.onDomainCall(u, token);
      }
      return new Response(JSON.stringify({ users: [{ userName: 'a@budgetsmart.io' }] }), { status: 200 });
    });
    vi.stubGlobal('fetch', spy);
    return calls;
  }

  it('impersonates the domain admin and calls the domain-scoped endpoint with THAT token', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubDomainFlow();

    await smartermailProvider.call('domain_users', { domain: 'budgetsmart.io' }, CRED, SERVER);

    const listCall = calls.find(c => c.url.includes('list-users'));

    // The whole bug in one assertion: the domain must NOT be in the path, and
    // the call must carry the impersonated token rather than the sysadmin one.
    expect(listCall).toBeDefined();
    expect(listCall!.url).not.toContain('budgetsmart.io');
    expect(listCall!.token).toBe('domain-token');
  });

  it('impersonates the domain ADMIN, never the mailbox being asked about', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubDomainFlow();

    await smartermailProvider.call('domain_users', { domain: 'budgetsmart.io' }, CRED, SERVER);

    const imp = calls.find(c => c.url.includes('impersonate-user'));

    expect(imp!.body).toEqual({ email: 'admin@budgetsmart.io' });
  });

  // Metadata only. If a mail endpoint ever appears on this token, the privacy
  // boundary this design rests on has quietly moved.
  it('never touches a mail or folder endpoint', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubDomainFlow();

    await smartermailProvider.call('domain_users', { domain: 'budgetsmart.io' }, CRED, SERVER);

    expect(calls.some(c => /\/mail\/|\/folders\//.test(c.url))).toBe(false);
  });

  it('reuses the impersonated token across calls instead of re-impersonating', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubDomainFlow();

    await smartermailProvider.call('domain_users', { domain: 'budgetsmart.io' }, CRED, SERVER);
    await smartermailProvider.call('domain_users', { domain: 'budgetsmart.io' }, CRED, SERVER);

    expect(calls.filter(c => c.url.includes('impersonate-user'))).toHaveLength(1);
  });

  it('keeps domains apart — a second domain gets its own token', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubDomainFlow();

    await smartermailProvider.call('domain_users', { domain: 'budgetsmart.io' }, CRED, SERVER);
    await smartermailProvider.call('domain_users', { domain: 'otherchurch.org' }, CRED, SERVER);

    expect(calls.filter(c => c.url.includes('impersonate-user'))).toHaveLength(2);
  });

  /**
   * A domain with no administrator is a real configuration, and the answer is
   * "add one", not "this endpoint is missing" — which is how the original
   * failure was read.
   */
  it('says a domain has no administrator rather than reporting a missing endpoint', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    stubDomainFlow({ admins: { domainAdmins: [] } });

    await expect(smartermailProvider.call('domain_users', { domain: 'budgetsmart.io' }, CRED, SERVER))
      .rejects
      .toThrow(/no domain administrator/);
  });

  it('accepts whichever container this build uses for the admin list', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubDomainFlow({ admins: { users: ['admin@budgetsmart.io'] } });

    await smartermailProvider.call('domain_users', { domain: 'budgetsmart.io' }, CRED, SERVER);

    expect(calls.find(c => c.url.includes('impersonate-user'))!.body)
      .toEqual({ email: 'admin@budgetsmart.io' });
  });

  it('falls through alias path variants and reports all of them when none work', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    stubDomainFlow({
      onDomainCall: () => new Response('not found', { status: 404 }),
    });

    // The point is the error names what was tried and where to look, instead of
    // leaving "404" to be read as "this feature does not exist".
    await expect(smartermailProvider.call('list_aliases', { domain: 'budgetsmart.io' }, CRED, SERVER))
      .rejects
      .toThrow(/settings\/domain\/aliases[\s\S]*Documentation\/api/);
  });

  it('stops at the first alias path that works', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubDomainFlow({
      onDomainCall: (url: string) => (url.includes('settings/domain/aliases')
        ? new Response(JSON.stringify({ aliases: [] }), { status: 200 })
        : new Response('not found', { status: 404 })),
    });

    await smartermailProvider.call('list_aliases', { domain: 'budgetsmart.io' }, CRED, SERVER);

    expect(calls.filter(c => c.url.includes('alias')).length).toBe(1);
  });

  it('requires a domain', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    stubDomainFlow();

    await expect(smartermailProvider.call('domain_users', {}, CRED, SERVER))
      .rejects
      .toThrow(/which domain/i);
  });
});

/**
 * Shared-mailbox reading.
 *
 * The allowlist IS the privacy control, so these tests are less about the happy
 * path than about proving the control cannot be bypassed: default-closed, exact
 * matching, and no leakage between mailboxes.
 */
describe('shared mailbox access', () => {
  const CRED = 'artivio@example.com:hunter2';
  const SERVER = 'https://mail.example.com';
  const TARGET = 'https://mail.example.com | support@budgetsmart.io, info@budgetsmart.io';

  function stubMailFlow() {
    const calls: Array<{ url: string; token: string; body?: any }> = [];
    vi.stubGlobal('fetch', vi.fn(async (url: string, init?: any) => {
      const u = String(url);
      calls.push({
        url: u,
        token: String(init?.headers?.Authorization ?? '').replace('Bearer ', ''),
        body: init?.body ? JSON.parse(init.body) : undefined,
      });
      if (u.includes('authenticate-user')) {
        return new Response(JSON.stringify({
          accessToken: 'sysadmin-token',
          accessTokenExpiration: new Date(Date.now() + 3600_000).toISOString(),
        }), { status: 200 });
      }
      if (u.includes('impersonate-user')) {
        return new Response(JSON.stringify({ impersonateAccessToken: 'mailbox-token' }), { status: 200 });
      }
      return new Response(JSON.stringify({
        messages: [{ uid: '42', from: 'a@b.com', subject: 'Help', date: '2026-08-12', isRead: false }],
      }), { status: 200 });
    }));
    return calls;
  }

  describe('parseTarget', () => {
    it('reads the server alone when no allowlist is given', () => {
      expect(parseTarget('https://mail.example.com')).toEqual({
        server: 'https://mail.example.com',
        readable: [],
      });
    });

    it('splits the server from the readable mailboxes', () => {
      expect(parseTarget(TARGET)).toEqual({
        server: 'https://mail.example.com',
        readable: ['support@budgetsmart.io', 'info@budgetsmart.io'],
      });
    });

    it('lowercases and trims, so casing in the config is not a silent denial', () => {
      expect(parseTarget('https://m.io |  Support@Example.COM ').readable)
        .toEqual(['support@example.com']);
    });
  });

  /**
   * Default-closed. A connection configured before mail reading existed has no
   * allowlist, and must not silently gain the ability to read mail when the
   * feature ships.
   */
  it('refuses every mailbox when no allowlist is configured', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    stubMailFlow();

    await expect(smartermailProvider.call('read_messages', { mailbox: 'support@budgetsmart.io' }, CRED, SERVER))
      .rejects
      .toThrow(/not permitted to read any mailbox/);
  });

  it('refuses a mailbox that is not on the list, and names the list', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubMailFlow();

    await expect(smartermailProvider.call('read_messages', { mailbox: 'ryan@budgetsmart.io' }, CRED, TARGET))
      .rejects
      .toThrow(/not on this connection's readable list/);

    // And crucially: it must refuse BEFORE impersonating anyone.
    expect(calls.some(c => c.url.includes('impersonate-user'))).toBe(false);
  });

  // Substring matching would make "upport@x.com" or "support@x.com.evil" pass.
  it('matches the address exactly, not as a substring', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    stubMailFlow();

    await expect(smartermailProvider.call('read_messages', { mailbox: 'support@budgetsmart.io.attacker.com' }, CRED, TARGET))
      .rejects
      .toThrow(/not on this connection's readable list/);
  });

  it('reads an allowlisted mailbox as that mailbox', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubMailFlow();

    const out = JSON.parse(await smartermailProvider.call(
      'read_messages',
      { mailbox: 'support@budgetsmart.io' },
      CRED,
      TARGET,
    ) as string);

    expect(calls.find(c => c.url.includes('impersonate-user'))!.body)
      .toEqual({ email: 'support@budgetsmart.io' });
    expect(calls.find(c => c.url.includes('mail/messages'))!.token).toBe('mailbox-token');
    expect(out.messages[0].subject).toBe('Help');
  });

  // The agent will read mail from strangers. It must be told, every time.
  it('labels message content as untrusted', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    stubMailFlow();

    const out = JSON.parse(await smartermailProvider.call(
      'read_messages',
      { mailbox: 'support@budgetsmart.io' },
      CRED,
      TARGET,
    ) as string);

    expect(out.note).toMatch(/UNTRUSTED/);
  });

  it('does not glue the allowlist onto the request URL', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubMailFlow();

    await smartermailProvider.call('read_messages', { mailbox: 'support@budgetsmart.io' }, CRED, TARGET);

    expect(calls.every(c => !c.url.includes('|'))).toBe(true);
    expect(calls.every(c => c.url.startsWith('https://mail.example.com/'))).toBe(true);
  });

  it('caps the page size at 100 however large a limit is asked for', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    const calls = stubMailFlow();

    await smartermailProvider.call('read_messages', { mailbox: 'support@budgetsmart.io', limit: 5000 }, CRED, TARGET);

    expect(calls.find(c => c.url.includes('mail/messages'))!.body.take).toBe(100);
  });

  it('gates list_folders and read_message on the same allowlist', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    stubMailFlow();

    await expect(smartermailProvider.call('list_folders', { mailbox: 'wendy@budgetsmart.io' }, CRED, TARGET))
      .rejects
      .toThrow(/not on this connection's readable list/);
    await expect(smartermailProvider.call('read_message', { mailbox: 'wendy@budgetsmart.io', uid: '1' }, CRED, TARGET))
      .rejects
      .toThrow(/not on this connection's readable list/);
  });

  it('still refuses to mint a token through the escape hatch', async () => {
    const { smartermailProvider } = await import('@/libs/plugins/smartermail');
    stubMailFlow();

    await expect(smartermailProvider.call(
      'smartermail_call',
      { path: 'settings/domain/impersonate-user', method: 'POST', body: { email: 'ryan@budgetsmart.io' } },
      CRED,
      TARGET,
    )).rejects.toThrow(/cannot be enabled/);
  });
});
